export enum AuthErrorCodes {
  AUTH_ERROR_GENERAL = 'AUTH_GENERAL',
  AUTH_ERROR_UNVERIFIED = 'ACCOUNT_UNVERIFIED',
  AUTH_ERROR_INACTIVE = 'ACCOUNT_DEACTIVATED',
  AUTH_ERROR_INCORRECT_PASSWORD = 'INVALID_PASSWORD',
  AUTH_ERROR_OTP_EXPIRED = 'OTP_EXPIRED',
  AUTH_ERROR_INCORRECT_OTP = 'OTP_INVALID',
  AUTH_ERROR_LOCKOUT = 'ACCOUNT_LOCKED',
  AUTH_SUCCESS_CODE = 'AUTH_SUCCESS',
  AUTH_OTP_REQUIRED = 'OTP_REQUIRED',
}

export interface ILogoutRequest {
  device: string
}
